apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: test-mks
  project: defaultproject
  labels:
    check3: value3
    check4: value4
spec:
  blueprint:
    name: default
    version: latest
  config:
    autoApproveNodes: true
    dedicatedMastersEnabled: true
    highAvailability: false
    kubernetesVersion: v1.25.2
    location: sanjose-us
    network:
      cni:
        name: Flannel
        version: 0.13.0
      ipv6:
        podSubnet: 2001:db8:42:0::/56
        serviceSubnet: 2001:db8:42:1::/112
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: ip-172-31-51-154
      operatingSystem: Ubuntu20.04
      privateip: 172.31.51.154
      interface: eth0
      roles:
      - Master
      ssh:
        ipAddress: 44.242.145.41
        port: "22"
        privateKeyPath: test-mks.pem
        username: ubuntu
    - arch: amd64
      hostname: ip-172-31-52-188
      operatingSystem: Ubuntu20.04
      privateip: 172.31.52.188
      roles:
      - Storage
      - Worker
      ssh:
        ipAddress: 35.88.0.115
        port: "22"
        privateKeyPath: test-mks.pem
        username: ubuntu 
    proxy:
      httpProxy: null
      httpsProxy: null
      noProxy: null
      proxyRootCA: null
      tlsTerminate: true
  type: mks
