kind: Trigger
apiVersion: pipeline.rafay.dev/v2
metadata:
  name: apache-trigger
  project: davidprivate
spec:
  triggerType: WebhookTrigger
  pipelineRef: apache-git-pipeline
  repositoryRef: training
  triggerConfig:
    webhook:
      configType: Github
  repositoryConfig:
    git:
      paths:
      - training/workloads/apache-custom-values.yaml
      revision: master
