kind: Trigger
apiVersion: pipeline.rafay.dev/v2
metadata:
  name: apache-trigger
  project: davidprivate
spec:
  triggerType: PeriodicSCMTrigger
  pipelineRef: apache-git-pipeline
  repositoryRef: training
  triggerConfig:
    periodicSCM:
      cronExpression: "*/5 * * * *"
  repositoryConfig:
    git:
      paths:
      - training/workloads/apache-custom-values.yaml
      revision: master
