apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: test-mks
  project: defaultproject
  labels:
    check1: value1
    check2: value2
spec:
  blueprint:
    name: default
    version: latest
  config:
    autoApproveNodes: true
    dedicatedMastersEnabled: false
    highAvailability: false
    kubernetesVersion: v1.24.6
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.19.1
      ipv6:
        podSubnet: 2001:db8:42:0::/56
        serviceSubnet: 2001:db8:42:1::/112
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: ip-172-31-49-249
      operatingSystem: Ubuntu20.04
      privateip: 172.31.49.249
      roles:
      - Master
      - Worker
      - Storage
      ssh:
        ipAddress: 35.84.39.36
        port: "22"
        privateKeyPath: test-mks.pem
        username: ubuntu
    proxy:
      httpProxy: null
      httpsProxy: null
      noProxy: null
      proxyRootCA: null
      tlsTerminate: true
  type: mks
