apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: argocd-blueprint
  project: demo
spec:
  base:
    name: default
    version: 1.18.0
  customAddons:
  - name: argo-cd
    version: v2.14.7
  defaultAddons:
    enableIngress: true
    enableLogging: false
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  sharing:
    enabled: false
  version: v1
