apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: standard-blueprint
  project: demo
spec:
  base:
    name: default
    version: 1.18.0
  customAddons:
  - name: vault-server
    version: v0.9.1
  - name: cert-manager
    version: v1.5.3
  defaultAddons:
    enableIngress: true
    enableLogging: false
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  sharing:
    enabled: false
  version: v1
