apiVersion: v1
kind: Service
metadata:
  name: speedtest
  labels:
    app: speedtest
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: speedtest

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
spec:
  selector:
    matchLabels:
      app: speedtest
  replicas: 1
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - name: speedtest
        image: adolfintel/speedtest:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    rafay.dev/dns: "true"
spec:
  rules:
  - host: speedtest-demo.run.rafay-edge.net
    http:
      paths:
      - backend:
          serviceName: speedtest
          servicePort: 80
