apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: cert-manager
  project: demo
spec:
  artifact:
    artifact:
      chartName: cert-manager
      chartVersion: 1.5.3
      repository: cert-manager-helm
      valuesPaths:
      #paths:
      - name: file://addon/examples/cert-manager-values.yaml
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: cert-manager
  sharing:
    enabled: false
  version: v1.5.3
