kind: Cluster
metadata:
  # cluster labels
  labels:
    env: dev
    type: eks-workloads
  name: demo-cluster
  project: defaultproject
spec:
  type: eks
  blueprint: default
  cloudprovider: AWS
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-cluster
  region: us-west-1
  version: "1.18"
  tags:
    'demo': 'true'
nodeGroups:
  - name: nodegroup-1
    instanceType: t3.xlarge
    desiredCapacity: 2
    volumeType: gp3
    volumeSize: 50
    privateNetworking: true
    iam:
      withAddonPolicies:
              albIngress: true
              autoScaler: true
              imageBuilder: true
              efs: true
