## Service paramaters
##
service:
  ## Service type
  ##
  type: LoadBalancer
  #type: NodePort
  ## HTTP Port
  ##
  port: 80
  ## HTTPS Port
  ##
  httpsPort: 443
  ##
replicaCount: 2

tolerations:
- key: "node/infra"
  operator: "Exists"
  effect: "NoSchedule"
