version: 2.1

orbs:
    jq: circleci/jq@2.2.0

jobs:
  build:
      docker:
        - image: cimg/python:3.9.2
      steps:
        - checkout
        - jq/install
        - run:
              name: Create Argocd Addon
              command: |
                python3 -m pip install pyyaml
                wget -q https://s3-us-west-2.amazonaws.com/rafay-prod-cli/publish/rctl-linux-amd64.tar.bz2
                tar -xf rctl-linux-amd64.tar.bz2
                chmod 0755 rctl
                ARGOCD_NAMESPACE="argocd"
                ADDON_TYPE=`cat addon/examples/argocd-spec.yaml |python -c 'import sys, yaml, json; y=yaml.safe_load(sys.stdin.read()); print(json.dumps(y))' | jq .spec.template.type | tr \" " " | awk '{print $1}' | tr -d "\n"`
                ADDON_NAME=`cat addon/examples/argocd-spec.yaml |python -c 'import sys, yaml, json; y=yaml.safe_load(sys.stdin.read()); print(json.dumps(y))' | jq .spec.addon | tr \" " " | awk '{print $1}' | tr -d "\n"`
                ./rctl create namespace $ARGOCD_NAMESPACE
                ./rctl create addon $ADDON_TYPE $ADDON_NAME --namespace $ARGOCD_NAMESPACE
                ./rctl create addon version -f addon/examples/argocd-spec.yaml
