apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: test-eks
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: dev-aws
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    iam:
      serviceAccounts:
        - attachPolicyARNs:
            - arn:aws:iam::1234567890:policy/policy
          metadata:
            name: demo
            namespace: default
        - attachPolicy:
            Statement:
              - Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Effect: Allow
                Resource:
                  - arn:aws:secretsmanager:us-west-2:1234567890:secret:demo
            Version: "2012-10-17"
          metadata:
            name: demo1
            namespace: test2
        - attachRoleARN: arn:aws:iam::1234567890:role/role1
          metadata:
            name: demo2
            namespace: default
      withOIDC: true
    identityMappings:
      accounts:
        - "1234567890"
      arns:
        - arn: arn:aws:iam::1234567890:user/user@email
          group:
            - system:masters
          username: user
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceType: t3.xlarge
      labels:
        app: infra
        dedicated: "true"
      maxSize: 2
      minSize: 2
      name: eks-test-ng-3
      taints:
      - effect: NoExecute
        key: team
        value: cloudengng
      version: "1.22"
      volumeSize: 80
      volumeType: gp3
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceType: t3.xlarge
      labels:
        app: infra
        dedicated: "true"
      maxSize: 2
      minSize: 2
      name: eks-test-ng-2
      taints:
      - effect: NoExecute
        key: appdaemon
        value: infradaemon
      - effect: NoSchedule
        key: dedicated
        value: "true"
      version: "1.22"
      volumeSize: 80
      volumeType: gp3
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceType: t3.xlarge
      labels:
        app: infra
        dedicated: "true"
      maxSize: 2
      minSize: 2
      name: eks-test-ng-1
      taints:
      - effect: NoExecute
        key: app
        value: infra
      - effect: NoSchedule
        key: dedicated
        value: "true"
      version: "1.22"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: test-eks
      region: us-west-2
      version: "1.22"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  proxyConfig: {}
  systemComponentsPlacement:
    daemonSetOverride:
      nodeSelectionEnabled: false
      tolerations:
      - effect: NoExecute
        key: appdaemon
        operator: Equal
        value: infradaemon
    nodeSelector:
      app: infra
      dedicated: "true"
    tolerations:
    - effect: NoExecute
      key: app
      operator: Equal
      value: infra
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: "true"
  type: aws-eks