# Usage: rctl create node-group eks -f node-group-config.yml
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-eks
  region: us-west-1

managedNodeGroups:
  - name: ng-1
    minSize: 2
    maxSize: 4
