kind: Cluster
metadata:
  name: br-fargate-test-prod
  project: prod
spec:
  type: eks
  cloudprovider: aws-broadridge-poc
  blueprint: default
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: br-fargate-test-dev
  region: us-west-1
  version: "1.19"
  
nodeGroups:
  - name: fargate-ng-11
    instanceType: t3.xlarge
    desiredCapacity: 1

fargateProfiles:
  - name: fp-dev
    selectors:
      # All workloads in the "jira" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: jira
