apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    rafay.dev/clusterName: demo-rafay-vmware
    rafay.dev/clusterType: vmware_vsphere
  name: demo-rafay-vmware
  project: demo
spec:
  blueprint:
    name: minimal
    version: latest
  cloudCredentials: vmwareaugust
  config:
    controlPlane:
      machineCount: 1
      sshAuthorizedKeys:
       - ssh-rsa 
        AAAAB3NzaC1yc2EAAAADAQABAAABAQDVt10K8xPo2lHI2EeHf/3pVUsSLA00b5yO
        9sk/4aEVmjim3tb1Dtt+t9b31W93k5vuLB1JsQXqUakHOGCpR0HKBOv3NR9odqTy
        5s57+2CZaiZ+5oYQ9hz1ugFZGg1NYeeM9z+/3KGJ0FYRC/HYN8u32OSWh9CXnQni
        7+bm6mw9PKJxaw8B6uOcs8ObbHaZaZ0XJw+pNStZlgk6ANcc5ScNs8DOug+41FIG
        YSMQtFY1N1NMvsPLqxEod0UlB8rvIvclB2ogX7zNV1hG8w6qr4qwj1clubEo54D2
        wwdJApI0LP4Yrn0zrnh2KKp2srcZK5Wh/+7Yl05yAHxbwR1fQkqH
      version: v1.23.5
    controlPlaneEndpointIP: 10.108.10.86
    datacenter: SDDC-Datacenter
    datastore: WorkloadDatastore
    network:
      cni:
        name: calico
        version: v3.22.0
      devices:
      - networkName: sddc-rafay-k8s
    proxy:
      enabled: false
    resourcePool: Compute-ResourcePool
    vmFolder: ankurptest
    vmTemplate: ubuntu-2004-kube-v1.23.5
    workerNodes:
      machineCount: 3
      sshAuthorizedKeys:
       - ssh-rsa 
        AAAAB3NzaC1yc2EAAAADAQABAAABAQDVt10K8xPo2lHI2EeHf/3pVUsSLA00b5yO
        9sk/4aEVmjim3tb1Dtt+t9b31W93k5vuLB1JsQXqUakHOGCpR0HKBOv3NR9odqTy
        5s57+2CZaiZ+5oYQ9hz1ugFZGg1NYeeM9z+/3KGJ0FYRC/HYN8u32OSWh9CXnQni
        7+bm6mw9PKJxaw8B6uOcs8ObbHaZaZ0XJw+pNStZlgk6ANcc5ScNs8DOug+41FIG
        YSMQtFY1N1NMvsPLqxEod0UlB8rvIvclB2ogX7zNV1hG8w6qr4qwj1clubEo54D2
        wwdJApI0LP4Yrn0zrnh2KKp2srcZK5Wh/+7Yl05yAHxbwR1fQkqH
      version: v1.23.5
  type: Vmware_vsphere